CREATE TABLE IF NOT EXISTS CH_ELEXIS_CORE_FINDINGS_OBSERVATION (
  ID varchar(25) DEFAULT NULL,
  lastupdate bigint(20) DEFAULT NULL,
  deleted char(1) DEFAULT '0',
  type char(8),
  referenced char(1) default '0',
  patientid varchar(80) DEFAULT NULL,
  encounterid varchar(80) DEFAULT NULL,
  performerid varchar(80) DEFAULT NULL,
  originuri varchar(255) DEFAULT NULL,
  decimalplace varchar(8) DEFAULT NULL,
  format longtext,
  script longtext,
  content longtext
);
INSERT INTO  CH_ELEXIS_CORE_FINDINGS_OBSERVATION (ID, patientid) VALUES ('VERSION','1.0.3');

CREATE INDEX CH_ELEXIS_CORE_FINDINGS_OBSERVATION_IDX1 ON CH_ELEXIS_CORE_FINDINGS_OBSERVATION (patientid);
CREATE INDEX CH_ELEXIS_CORE_FINDINGS_OBSERVATION_IDX2 ON CH_ELEXIS_CORE_FINDINGS_OBSERVATION (encounterid);
CREATE INDEX CH_ELEXIS_CORE_FINDINGS_OBSERVATION_IDX3 ON CH_ELEXIS_CORE_FINDINGS_OBSERVATION (originuri);