CREATE TABLE IF NOT EXISTS CH_ELEXIS_CORE_FINDINGS_LOCALCODING (
  ID varchar(25) DEFAULT NULL,
  lastupdate bigint(20) DEFAULT NULL,
  deleted char(1) DEFAULT '0',
  code varchar(25) DEFAULT NULL,
  display longtext,
  mapped longtext
);
INSERT INTO  CH_ELEXIS_CORE_FINDINGS_LOCALCODING (ID, code) VALUES ('VERSION','1.0.0');

CREATE INDEX CH_ELEXIS_CORE_FINDINGS_LOCALCODING_IDX1 ON CH_ELEXIS_CORE_FINDINGS_LOCALCODING (code);