CREATE TABLE IF NOT EXISTS CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION (
  ID varchar(25) DEFAULT NULL,
  lastupdate bigint(20) DEFAULT NULL,
  deleted char(1) DEFAULT '0',
  patientid varchar(80) DEFAULT NULL,
  encounterid varchar(80) DEFAULT NULL,
  content longtext
);
INSERT INTO  CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION (ID, patientid) VALUES ('VERSION','1.0.0');

CREATE INDEX CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION_IDX1 ON CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION (patientid);
CREATE INDEX CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION_IDX2 ON CH_ELEXIS_CORE_FINDINGS_CLINICALIMPRESSION (encounterid);